Ffm 908
drone/ff-android-client-sdk pull request #12
Opened 2021-06-01 12:02 UTC by milos85vasic-harness

This pull request contains the following changes:

- Metrics implementation for the Android (with basic unit tests)
- Feature configurations obtain mechanism
- Unit tests updates for easier future tests writing and extension
- Basic SDK documentation on how to use Metrics.

2021-06-02 07:02 UTC, davejohnston approved these changes
This looks good to me

2021-06-02 21:49 UTC, rushabh-harness commented on README.md
> +            .enableStream(true)
this should be default configuration, no need to define it explicitly

2021-06-02 21:50 UTC, rushabh-harness commented on README.md
> +            .enableAnalytics(true)
same thing for analytics

2021-06-02 21:50 UTC, rushabh-harness commented on README.md
> +            .pollingInterval(10)
what is the default polling interval acc to playbook ?

2021-06-02 21:56 UTC, rushabh-harness commented on cfsdk/src/main/java/io/harness/cfsdk/cloud/model/Target.java
> +    private boolean isPrivate; // If the target is private
There is only 1 target in the system so not sure what this means if the target is private

2021-06-02 21:56 UTC, rushabh-harness commented on cfsdk/src/main/java/io/harness/cfsdk/cloud/model/Target.java
> +    private Set<String> privateAttributes; // Custom set to set the attributes which are private
Does it make sense to have private attributes in client SDK ?

2021-06-02 21:58 UTC, rushabh-harness requested changes
Please go over the comments I have listed in the PR. Let me know what you feel

2021-06-03 08:42 UTC, milos85vasic-harness commented
@rushabh-harness I have addressed all of your comments since each of them Is valid. Please look at my latest changes (my last commit) and let me know once you finish the review. Thank you!

2021-06-04 16:15 UTC, rushabh-harness approved these changes

2021-06-07 08:22 UTC, merged